name: asimov
base: core22
version: 'auto'
summary: ASIMOV CLI Snap
description: "Bundles a prebuilt binary (gzipped) into a snap."

grade: devel
confinement: classic

parts:
  asimov-cli:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull

      ARCH=${ARCH_NAME:-x86-gnu}

      # ASIMOV CLI
      BINARY_NAME="asimov-linux-${ARCH}"
      FILE="${BINARY_NAME}.gz"
      wget -O "$FILE" "https://github.com/asimov-platform/asimov-cli/releases/latest/download/$FILE"
      gunzip "$FILE"
      chmod +x "${FILE%.gz}"

      # ASIMOV MODULE CLI
      BINARY_NAME="module-cli-linux-${ARCH}"
      FILE="${BINARY_NAME}.gz"
      wget -O "$FILE" "https://github.com/asimov-platform/asimov-module-cli/releases/latest/download/$FILE"
      gunzip "$FILE"
      chmod +x "${FILE%.gz}"

      # ASIMOV DATASET CLI
      BINARY_NAME="asimov-linux-${ARCH}"
      FILE="${BINARY_NAME}.gz"
      wget -O "$FILE" "https://github.com/asimov-platform/asimov-dataset-cli/releases/latest/download/$FILE"
      gunzip "$FILE"
      chmod +x "${FILE%.gz}"

    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mv "asimov-linux-${ARCH}" "$SNAPCRAFT_PART_INSTALL/bin/asimov"
      mv "module-cli-linux-${ARCH}" "$SNAPCRAFT_PART_INSTALL/bin/asimov-module"
      mv "asimov-linux-${ARCH}" "$SNAPCRAFT_PART_INSTALL/bin/asimov-dataset"
      snapcraftctl build

apps:
  asimov:
    command: bin/asimov
