name: asimov
base: core22
version: 'auto'
summary: ASIMOV CLI Snap
description: "Bundles prebuilt ASIMOV CLI and subcommands into a snap."

grade: devel
confinement: classic

parts:
  asimov-cli:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull

      ARCH=${CRAFT_TARGET_ARCH:-x86_64}
      PLATFORM=""
      case "$ARCH" in
        amd64|x86_64)   PLATFORM="x86-gnu" ;;
        arm64|aarch64)  PLATFORM="arm-gnu" ;;
        *) echo "Unsupported architecture: $ARCH" && exit 1 ;;
      esac

      for name in asimov module-cli asimov; do
        FILE="${name}-linux-${PLATFORM}.gz"
        wget -O "${name}.gz" "https://github.com/asimov-platform/${name}/releases/latest/download/${FILE}"
        gunzip "${name}.gz"
        chmod +x "${name}"
      done

    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mv asimov "$SNAPCRAFT_PART_INSTALL/bin/asimov"
      mv module-cli "$SNAPCRAFT_PART_INSTALL/bin/asimov-module"
      mv dataset-cli "$SNAPCRAFT_PART_INSTALL/bin/asimov-dataset"
      snapcraftctl build

apps:
  asimov:
    command: bin/asimov
