name: asimov
base: core22
version: 'auto'
summary: ASIMOV CLI Snap
description: "Bundles prebuilt ASIMOV CLI binaries (asimov + subcommands) into a snap."

grade: devel
confinement: classic

parts:
  asimov-cli:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull

      ARCH="${SNAPCRAFT_ARCH_TRIPLET}"

      wget -O asimov.gz "https://github.com/asimov-platform/asimov-cli/releases/latest/download/asimov-linux-${ARCH}.gz"
      wget -O module.gz "https://github.com/asimov-platform/asimov-module-cli/releases/latest/download/module-cli-linux-${ARCH}.gz"
      wget -O dataset.gz "https://github.com/asimov-platform/asimov-dataset-cli/releases/latest/download/asimov-linux-${ARCH}.gz"

      gunzip asimov.gz
      gunzip module.gz
      gunzip dataset.gz

      mv module asimov-module
      mv dataset asimov-dataset

      chmod +x asimov asimov-module asimov-dataset

    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mv asimov asimov-module asimov-dataset "$SNAPCRAFT_PART_INSTALL/bin/"
      snapcraftctl build

apps:
  asimov:
    command: bin/asimov
