name: asimov
base: core22
version: 'auto'
summary: ASIMOV CLI Snap
description: "Bundles a prebuilt binary (gzipped) into a snap."

grade: devel
confinement: classic

parts:
  asimov-cli:
    plugin: dump
    source: .
    override-pull: |
      snapcraftctl pull

      ARCH=${ARCH_NAME:-x86-gnu}
    
      declare -A projects=(
        [asimov]="asimov-cli:asimov-linux-${ARCH}"
        [asimov-module]="asimov-module-cli:module-cli-linux-${ARCH}" # TODO change artifact name
        [asimov-dataset]="asimov-dataset-cli:asimov-linux-${ARCH}" # TODO change artifact name
      )
    
      for bin in "${!projects[@]}"; do
        IFS=":" read -r repo binary <<< "${projects[$bin]}"
        FILE="${binary}.gz"
        
        echo "Downloading $FILE from $repo"
        wget "https://github.com/asimov-platform/${repo}/releases/latest/download/$FILE"
        gunzip "$FILE"
        chmod +x "$binary"
        mv "$binary" "$bin"
      done

    override-build: |
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mv asimov "$SNAPCRAFT_PART_INSTALL/bin/asimov"
      mv asimov-module "$SNAPCRAFT_PART_INSTALL/bin/asimov-module"
      mv asimov-dataset "$SNAPCRAFT_PART_INSTALL/bin/asimov-dataset"
      snapcraftctl build

apps:
  asimov:
    command: bin/asimov
    environment:
      PATH: "$SNAP/bin:$PATH"
