name: Update Flatpak YAML to use latest version of ASIMOV CLI

on:
  workflow_dispatch:
  schedule:
    # At 02:00 every night – https://crontab.guru/#0_2_*_*_*
    - cron: "0 2 * * *"

jobs:
  updateFlatpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Flatpak YAML
        shell: bash
        run: |
          set -euxo pipefail

          FILE="flatpak/so.asimov.cli.yaml"

          declare -A projects=(
            [asimov]="asimov-cli"
            [asimov-module]="asimov-module-cli"
            [asimov-dataset]="asimov-dataset-cli"
          )

          declare -A filenames=(
            [asimov,x86_64]="asimov-linux-x86-gnu.gz"
            [asimov,aarch64]="asimov-linux-arm-gnu.gz"
            [asimov-module,x86_64]="module-cli-linux-x86-gnu.gz"
            [asimov-module,aarch64]="module-cli-linux-arm-gnu.gz"
            [asimov-dataset,x86_64]="asimov-linux-x86-gnu.gz"
            [asimov-dataset,aarch64]="asimov-linux-arm-gnu.gz"
          )

          for key in "${!projects[@]}"; do
            project="${projects[$key]}"
            version=$(curl -s "https://api.github.com/repos/asimov-platform/${project}/releases/latest" | jq -r .tag_name)

            for arch in x86_64 aarch64; do
              file="${filenames[${key},${arch}]}"
              url="https://github.com/asimov-platform/${project}/releases/download/${version}/${file}"
              sha=$(curl -sL "${url}.sha256" | cut -d ' ' -f1)

              # Update URL
              sed -i "s|https://github.com/asimov-platform/${project}/releases/download/[^/]*/${file}|${url}|" "$FILE"

              # Update sha256
              sed -i -E "/${file}/{n;s/(sha256: \")[^\"]*(\")/\1${sha}\2/}" "$FILE"
            done
          done

#          if ! git diff --exit-code "$FILE"; then
#            git add "$FILE"
#            git commit -m "Update Flatpak YAML to latest ASIMOV versions"
#            git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:"${GITHUB_REF#refs/heads/}"
#          else
#            echo "No changes detected."
#          fi
