name: Update flake.nix to use latest ASIMOV CLI versions

on:
  push:
#  workflow_dispatch:
#  schedule:
#    - cron: "0 2 * * *"

jobs:
  updateAsimov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch latest versions and update flake.nix
        shell: bash
        run: |
          set -euxo pipefail

          update_entry() {
            project="$1"
            binary="$2"

            if [[ "$project" == "asimov-cli" ]]; then
              platforms=(
                "x86_64-linux:asimov-linux-x86-gnu.gz"
                "aarch64-linux:asimov-linux-arm-gnu.gz"
                "x86_64-darwin:asimov-macos-x86.gz"
                "aarch64-darwin:asimov-macos-arm.gz"
              )
            elif [[ "$project" == "asimov-module-cli" ]]; then
              platforms=(
                "x86_64-linux:asimov-module-cli-linux-x86-gnu.gz"
                "aarch64-linux:asimov-module-cli-linux-arm-gnu.gz"
                "x86_64-darwin:asimov-module-cli-macos-x86.gz"
                "aarch64-darwin:asimov-module-cli-macos-arm.gz"
              )
            elif [[ "$project" == "asimov-dataset-cli" ]]; then
              platforms=(
                "x86_64-linux:asimov-dataset-cli-linux-x86-gnu.gz"
                "aarch64-linux:asimov-dataset-cli-linux-arm-gnu.gz"
                "x86_64-darwin:asimov-dataset-cli-macos-x86.gz"
                "aarch64-darwin:asimov-dataset-cli-macos-arm.gz"
              )
            fi

            latest_version=$(curl -s "https://api.github.com/repos/asimov-platform/${project}/releases/latest" | jq -r .tag_name)

            for item in "${platforms[@]}"; do
              sys="${item%%:*}"
              file="${item##*:}"
              sha_url="https://github.com/asimov-platform/${project}/releases/download/${latest_version}/${file}.sha256"
              sha=$(curl -sL "$sha_url" | cut -d ' ' -f1)

              sed -i -E "s|(${sys}\"[[:space:]]*=.*${binary}.*${file}\";[[:space:]]*sha256[[:space:]]*=[[:space:]]*\")[^\"]*(\";)|\1${sha}\2|" nix/flake.nix
            done

            sed -i -E "s|(${binary}[[:space:]]*=[[:space:]]*\")[^\"]*(\";)|\1${latest_version}\2|" nix/flake.nix
          }

          update_entry "asimov-cli"         "asimov"
          update_entry "asimov-module-cli"  "asimov-module"
          update_entry "asimov-dataset-cli" "asimov-dataset"

          if ! git diff --exit-code nix/flake.nix; then
            git add nix/flake.nix
            git commit -m "Update ASIMOV versions in flake.nix"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF##*/}
          fi
