name: Update flake.nix to use latest ASIMOV CLI versions

on:
  push:
#  workflow_dispatch:
#  schedule:
#    - cron: "0 2 * * *"

jobs:
  updateAsimov:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch latest versions and update flake.nix
        shell: bash
        run: |
          set -euxo pipefail

          flake_file="nix/flake.nix"

          update_project() {
            local project="$1"
            local key="$2"
            declare -a platforms
            declare -a filenames

            case "$project" in
              asimov-cli)
                platforms=("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin")
                filenames=("asimov-linux-x86-gnu.gz" "asimov-linux-arm-gnu.gz" "asimov-macos-x86.gz" "asimov-macos-arm.gz")
                ;;
              asimov-module-cli)
                platforms=("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin")
                filenames=("asimov-module-cli-linux-x86-gnu.gz" "asimov-module-cli-linux-arm-gnu.gz" "asimov-module-cli-macos-x86.gz" "asimov-module-cli-macos-arm.gz")
                ;;
              asimov-dataset-cli)
                platforms=("x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin")
                filenames=("asimov-dataset-cli-linux-x86-gnu.gz" "asimov-dataset-cli-linux-arm-gnu.gz" "asimov-dataset-cli-macos-x86.gz" "asimov-dataset-cli-macos-arm.gz")
                ;;
              *)
                echo "Unknown project: $project"
                exit 1
                ;;
            esac

            version=$(curl -s "https://api.github.com/repos/asimov-platform/${project}/releases/latest" | jq -r .tag_name)

            echo "Updating $project to version $version"

            # Update the version string
            sed -i -E "/versions\s*=\s*\{/,/^\s*\}/ s|(${key}\s*=\s*\")[^\"]*(\";)|\1${version}\2|" "$flake_file"

            for i in "${!platforms[@]}"; do
              platform="${platforms[$i]}"
              filename="${filenames[$i]}"
              sha_url="https://github.com/asimov-platform/${project}/releases/download/${version}/${filename}.sha256"
              sha=$(curl -sL "$sha_url" | cut -d ' ' -f1)

              echo "Updating sha256 for $platform -> $filename"

              # Only update the sha256 field, match by key, not filename
              sed -i -E "/haches\s*=\s*\{/,/^\s*\}/ s|(${key}\s*=\s*\")[^\"]*(\";)|\1${sha}\2|" "$flake_file"
            
            done
          }

          update_project "asimov-cli"         "asimov"
          update_project "asimov-module-cli"  "asimov-module"
          update_project "asimov-dataset-cli" "asimov-dataset"

          if ! git diff --exit-code nix/flake.nix; then
            echo "Changes detected. Committing..."
            git add nix/flake.nix
            git commit -m "Update ASIMOV versions and hashes in flake.nix"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF##*/}
          else
            echo "No changes detected. Skipping commit."
          fi
